name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.3 # Use the desired Go version

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Build binary
        run: go build -o app main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: go-binary
          path: app
